name: CI

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  app-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: app

      - name: Build project
        run: npm run build --if-present
        working-directory: app

      - name: Format check
        run: npm run format:check
        working-directory: app

      - name: Translate parse
        run: npm run translate-parse
        working-directory: app

      - name: Translation check
        run: node translation-check.js
        working-directory: app

      - name: Lint
        run: npm run lint
        working-directory: app

      - name: Test
        run: npm run test
        working-directory: app
